### ISSUE TITLE
The model `gpt-4-1106-preview` does not exist or you do not have access to it.

### ISSUE THREAD

**Issue by tailerteilor** [GregorD1A1/TinderGPT#3]
(env) PS C:\Users\engdf\TinderGPT> python main.py --head
Creating base...
Starting driver
Driver activated
Traceback (most recent call last):
  File "C:\Users\engdf\TinderGPT\main.py", line 135, in <module>
    tinder_connector = TinderConnector(driver)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\driver\connectors\tnd_conn.py", line 40, in __init__
    self.translate_rise_msg_if_needed()
  File "C:\Users\engdf\TinderGPT\driver\connectors\tnd_conn.py", line 180, in translate_rise_msg_if_needed
    rise_msg = translate_rise_msg(orig_rise_msg)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\AI_logic\misc.py", line 18, in translate_rise_msg
    return chain.invoke({'message': message, 'language': language})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\langchain\schema\runnable\base.py", line 1202, in invoke
    input = step.invoke(
            ^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\langchain\chat_models\base.py", line 142, in invoke
    self.generate_prompt(
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\langchain\chat_models\base.py", line 459, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\langchain\chat_models\base.py", line 349, in generate
    raise e
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\langchain\chat_models\base.py", line 339, in generate
    self._generate_with_cache(
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\langchain\chat_models\base.py", line 492, in _generate_with_cache
    return self._generate(
           ^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\langchain\chat_models\openai.py", line 365, in _generate
    response = self.completion_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\langchain\chat_models\openai.py", line 303, in completion_with_retry
    return _completion_with_retry(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\engdf\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\langchain\chat_models\openai.py", line 301, in _completion_with_retry
    return self.client.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\engdf\TinderGPT\env\Lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4-1106-preview` does not exist or you do not have access to it.
(env) PS C:\Users\engdf\TinderGPT> dir

**Comment by GregorD1A1** [comment]
Hey! Most probable you have no access to gpt-4/gpt-4-turbo models at your openAI account. You need to prepaid 5$ (if I remember good) to make access to it.

**Comment by tailerteilor** [comment]
![image](https://github.com/GregorD1A1/TinderGPT/assets/2882828/e37da16a-6d39-4790-a35f-99d6991f967e)

**Comment by GregorD1A1** [comment]
I mean you need access to gpt-4 through API, you don't need ChatGPT plus.
